### PR TITLE
sticker: 0.6.1 -> 0.7.0

### PR DESCRIPTION
**Pull request by danieldk**
I have also changed the package name from `rust_sticker-utils` to `sticker`.

### CODE REVIEW

**Review by sebpuetz — APPROVED** [review]
Is there something significant about the distinction between ’src’ and ’srcs’? Clearer distinction between variable and attributes?

**Comment by danieldk** [comment]
> Is there something significant about the distinction between ’src’ and ’srcs’? Clearer distinction between variable and attributes?

I made the attribute set recursive (`rec`) on order to use `pname` in defining `name`. However, then

```
src = "${src}/sticker-utils";
```

`src` shadows the outer `src` and we have an infinite recursion.

I guess there is a way of accessing the shadowed variable. Normally `inherit src;` would do the trick, but here we do not want to inherit `src` but actually add something.

Another approach would be to introduce `pname` in a `let`-binding, so that the attr set does not need to be recursive.

Maybe I should rename `srcs` to `sticker_src` to be more descriptive.

**Comment by danieldk** [comment]
Builds are failing due to a cachix timeout. This was already reported upstream:

https://github.com/cachix/cachix/issues/234

**Comment by sebpuetz** [comment]
Thanks for clearing up the `rec`, didn't know what that was about before ;)

**Pull request merged**
