### PR TITLE
de-ner-ud-small: init at 20190928

### PR DESCRIPTION
**Pull request by danieldk**

### CODE REVIEW

**Comment by danieldk** [comment]
After this, we have all German models covered, except for topological field analysis. It would be nice to have a topological field analysis model that takes concatenated universal tags and STTS tags as input.

@sebpuetz maybe you could add TFs to the data set if I point you to the right data?

**Comment by sebpuetz** [comment]
> After this, we have all German models covered, except for topological field analysis. It would be nice to have a topological field analysis model that takes concatenated universal tags and STTS tags as input.
> 
> @sebpuetz maybe you could add TFs to the data set if I point you to the right data?

You mean, annotate TFs on a dataset with the extended tagset? Sure

**Comment by danieldk** [comment]
> > After this, we have all German models covered, except for topological field analysis. It would be nice to have a topological field analysis model that takes concatenated universal tags and STTS tags as input.
> > @sebpuetz maybe you could add TFs to the data set if I point you to the right data?
> 
> You mean, annotate TFs on a dataset with the extended tagset? Sure

That would be great!

Non-gold tags (shuffled, but sentences do have identifiers):

turing-sfb:/home/daniel/exp/tdz-ud/nongold-ner

Gold tags (note though that the feature separator is `=`, which should be replaced by `:`):

turing-sfb:/home/daniel/exp/tdz-ud/gold/tdz11-ud.conll

There already is a `TopoField` feature, but these are the topological fields as in the UD version of TüBa-D/Z. If we add a `tf` feature as usual, all should be fine.

**Comment by sebpuetz** [comment]
Where can I find release 11 of tüba d/z? I'll need that to get the gold tfs

**Comment by danieldk** [comment]
I am currently rsyncing it to `/data/treebanks/tuebadz/r11`. Can take a couple of minutes over the VPN.

**Comment by sebpuetz** [comment]
All can be found under `/home/sebastian/topo-ud`. I annotated topological fields under `tf` as usual for both gold and nongold on all partitions and also for the full gold version. In the gold version I replaced all `=` inside the features column by `:`.

**Comment by danieldk** [comment]
Great, thanks! I'll copy them and train a new model. This would mean that all the annotations can be produced with the UD models.

**Pull request merged**
