### PR TITLE
python3Packages.sticker: init at 0.1.0

### PR DESCRIPTION
**Pull request by danieldk**

### CODE REVIEW

**Comment by danieldk** [comment]
This adds the sticker Python module. To build the module, we need `pyo3-pack`/`maturin`. nixpkgs 19.03 has an older `pyo3-pack` that does not have the needed parameters. So, we have two options: (1) add a derivation of `maturin` as well; (2) assume that we have nixpkgs 19.09 + bump up CI to build against 19.09. Since 19.09 will be out any day now, I am inclined to go for the second option.

**Comment by sebpuetz** [comment]
One of the CI builds segfaulted while installing nix?

**Comment by danieldk** [comment]
> One of the CI builds segfaulted while installing nix?

That happens quite often, there seems to be some weirdness with Travis CI, never happened on sr.ht CI. Upstream issue:

https://github.com/NixOS/nix/issues/3068

**Comment by sebpuetz** [comment]
> This adds the sticker Python module. To build the module, we need `pyo3-pack`/`maturin`. nixpkgs 19.03 has an older `pyo3-pack` that does not have the needed parameters. So, we have two options: (1) add a derivation of `maturin` as well; (2) assume that we have nixpkgs 19.09 + bump up CI to build against 19.09. Since 19.09 will be out any day now, I am inclined to go for the second option.

I'm not deep enough into nix to know whether people stick around on old versions of nixpkgs. Since it's a package repository, I wouldn't expect that since people probably want new and up-to-date versions available?

**Comment by danieldk** [comment]
> I'm not deep enough into nix to know whether people stick around on old versions of nixpkgs. Since it's a package repository, I wouldn't expect that since people probably want new and up-to-date versions available?

nixpkgs versions are supported with security updates until a month after the new release. So, if 19.09 is released today, then 19.03 will be supported until Nov 5. So, generally people would want to track the latest stable version.

The only exception is if you want to have a fully reproducible package (e.g. for a scientific article), then you would pin nixpkgs to a particular commit.

Of course, in the end it is a minor issue anyway. You can mix any version of nixpkgs. E.g. if you are running NixOS 19.03, nothing prevents you to use nixpkgs-19.09 or nixpkgs-unstable for a single package. Before switching to NixOS/nixpkgs unstable as my main OS, I'd run a stable version and several packages from unstable. (Vice versa, you could also use a 17.03 package with its 17.03 dependencies on nixpkgs 19.09.) The only downside of mixing different nixpkgs versions is that the store will contain multiple versions of some packages (e.g. glibc). But who cares if you have >= 500GB storage? ;)

**Comment by danieldk** [comment]
I'll merge this, since there seem to be no objections ;) and I shouldn't expect too much feedback on Nix derivations anyway.

**Pull request merged**
